spring.application.name=LoaPlan
server.port=8070
server.address=0.0.0.0
frontend.port=5173
frontend.ip=192.168.0.103

#frontend.ip=192.168.219.101

##########################################
# ? ??? ?? URL (?? ?? prefix)
##########################################

# ???
#app.server-url=http://localhost:${server.port}

# ip?
app.server-url=http://${frontend.ip}:${server.port}

#??? ???
#app.server-url=https://loaplan.com

# Lost Ark API JWT Key
lostark.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDA1ODc2NTMifQ.mYarBk0gWzRmSkVJ0hm_H68Y3mf8sOrbvQu22GrVBYYM5xMhh5z0-Hj29iVnuqzOo3FOEBR9dDTcDX-_nOMuM2DSS4KJUkCDdaTMgqaqFbd8eNW3nsxmZNifzuybmpp5PD8tev9PAPtaE2s7cuVUNRDjbvFOqt81mhb_Gj4HTlo4SGtqHwysCdMi5aHOAHxkiUnXpmqPvia90bUQVl3Tpuc2thKKiODxnyOSeNbcgcMMrYT5bzAgJsue45oI4hK57xgRqGehkMuW7zBHZyMM1raMbfz3gkJtIACRGHALIGLheGEYucXUaU09lS9U5xlr_0FdQQnbe8zu8XShW2Js8g

app.upload.dir=uploads




spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# MariaDB ?? ??
spring.datasource.url=jdbc:mariadb://localhost:3306/lostark?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=5700
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.servlet.multipart.resolve-lazily=true


spring.output.ansi.enabled=always


spring.security.oauth2.client.registration.google.client-id=605170723465-cs3808jnp8ies7tokvaqd5qmke0ag6b7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
